version: '3.3'

services:
  app:
    image: yaledoc/epcis_open_api:latest  #epcis_open_api:1.0
    #build: .
    container_name: epcisOpenAPI
    ports:
      - "3045:3045"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
    command: ["node", "index.js"]
